### ISSUE TITLE
Can't find .so file

### ISSUE THREAD

**Issue by komal2110** [thatbrguy/Deep-Stream-ONNX#6]
I compiled the parser using "make -C custom_bbox_parser". which does not save .so file and gives following output.

make: Entering directory '/home/Deepstream-App/Deep-Stream-ONNX/custom_bbox_parser'
make: Nothing to be done for 'DEEPSTREAM_PATH'.
make: Leaving directory '/home/Deepstream-App/Deep-Stream-ONNX/custom_bbox_parser'

Please help me to resolve this. Thank you. @thatbrguy

**Comment by thatbrguy** [comment]
It could be that your `Makefile` is not setup properly. Could you please share the first four lines of your `Makefile`?

**Comment by komal2110** [comment]
Yes it was a problem specifying the path in Makefile. The problem is solved.
Thank you for the response. @thatbrguy

**Comment by thatbrguy** [comment]
Glad it worked out! I'll close this issue then.

**Comment by alphapibeta** [comment]
Hello I am facing this issue and here is my **Makefile**, can you please help me?
<img width="1436" alt="Screenshot 2020-06-20 at 1 07 16 AM" src="https://user-images.githubusercontent.com/49142689/85174236-9ac82a00-b292-11ea-8fed-8f5c120965d5.png">

**Comment by thatbrguy** [comment]
Hi @alphapibeta, sorry for the late response. In case you have not solved it yet, can you share the exact error message that you received while encountering this problem?

Also, I see that you are using DeepStream 5.0, whereas this repository uses v4.0. If you are sure that your paths are set correctly and the issue is still not resolved, you can try using v4.0 to see if that works. If not, feel free to open a new issue with a description of the exact error that you are facing!
